"""Tyler digest: open errands and decision blockers rolled up across projects.

ADR 0016. Each project's ``00 Tasks/TYLER.md`` is the source of truth for Tyler's
personal errands; the production ``00 Tasks/TASKS.md`` ``DECISION`` lane holds the
calls only Tyler can make that block production. This module reads both, never
writes them, and renders one Markdown digest (``_tools/TYLER-TODAY.md`` when the
CLI writes it). The digest is a view: regenerated, never edited.

Parsing is line-based and deliberately shallow: unchecked checkbox lines under any
heading before ``## Done`` are open items. A list that does not follow the template
still parses; a missing file is reported as missing, not as empty - absence and
"nothing to do" must never read alike (ADR 0004).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path

from .scan import DriveInventory

TYLER_PATH = "00 Tasks/TYLER.md"
TASKS_PATH = "00 Tasks/TASKS.md"
DIGEST_NAME = "TYLER-TODAY.md"

_CHECKBOX = re.compile(r"^\s*- \[ \] (?P<body>.+)$")
_HEADING = re.compile(r"^## (?P<name>.+?)\s*$")
# Item text runs long on real lists (211 Centre lines carry full audit detail);
# the digest is a scan view, not the list, so bodies are clipped.
_CLIP = 160


@dataclass(frozen=True)
class DigestItem:
    id: str  # Y-NNN / T-NNN when present, else ""
    text: str
    section: str  # heading the item sat under: Now, Next, In progress, ...
    claim: str  # "claimed YYYY-MM-DD by <name>" when present, else ""


@dataclass(frozen=True)
class ProjectDigest:
    name: str
    errands: tuple[DigestItem, ...] = ()
    decisions: tuple[DigestItem, ...] = ()
    tyler_missing: bool = False
    tasks_missing: bool = False


@dataclass(frozen=True)
class Digest:
    drive: str
    projects: tuple[ProjectDigest, ...] = ()

    @property
    def errand_count(self) -> int:
        return sum(len(p.errands) for p in self.projects)

    @property
    def decision_count(self) -> int:
        return sum(len(p.decisions) for p in self.projects)


def _clip(text: str) -> str:
    text = " ".join(text.split())
    return text if len(text) <= _CLIP else text[: _CLIP - 1].rstrip() + "…"


def _parse_items(text: str, *, lane: str | None = None) -> tuple[DigestItem, ...]:
    """Open checkbox items before ``## Done``; ``lane`` keeps only that lane tag."""
    items: list[DigestItem] = []
    section = ""
    for line in text.splitlines():
        heading = _HEADING.match(line)
        if heading:
            section = heading.group("name")
            if section.lower().startswith("done"):
                break
            continue
        checkbox = _CHECKBOX.match(line)
        if not checkbox:
            continue
        body = checkbox.group("body").strip()
        if lane and f"`{lane}`" not in body:
            continue
        ident = ""
        idmatch = re.match(r"(?:\*\*)?(?P<id>[YT]-\d+)", body)
        if idmatch:
            ident = idmatch.group("id")
        claim = ""
        claimmatch = re.search(r"claimed \d{4}-\d{2}-\d{2} by [^.*]+", body)
        if claimmatch:
            claim = claimmatch.group(0).strip()
        items.append(DigestItem(id=ident, text=_clip(body), section=section, claim=claim))
    return tuple(items)


def _read(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8-sig")
    except (OSError, UnicodeDecodeError):
        return None


def collect(inventory: DriveInventory) -> Digest:
    projects: list[ProjectDigest] = []
    # Sorted by name: scan order is the filesystem's, which differs by OS.
    for inv in sorted(inventory.projects, key=lambda p: p.name):
        tyler_text = _read(inv.path / TYLER_PATH)
        tasks_text = _read(inv.path / TASKS_PATH)
        projects.append(
            ProjectDigest(
                name=inv.name,
                errands=_parse_items(tyler_text) if tyler_text is not None else (),
                decisions=(
                    _parse_items(tasks_text, lane="DECISION") if tasks_text is not None else ()
                ),
                tyler_missing=tyler_text is None,
                tasks_missing=tasks_text is None,
            )
        )
    return Digest(drive=inventory.map.drive, projects=tuple(projects))


def render(digest: Digest, *, generated: date | None = None) -> str:
    generated = generated or date.today()
    lines = [
        f"# Tyler today - {generated.isoformat()}",
        "",
        f"Generated by `atlas tyler` from each project's `00 Tasks/TYLER.md` and the "
        f"`DECISION` lane of `00 Tasks/TASKS.md` ({digest.drive}). "
        "Never edit this file - edit the project list and regenerate.",
        "",
        f"**{digest.errand_count} errands / {digest.decision_count} decisions blocking production**",
    ]
    for project in digest.projects:
        lines += ["", f"## {project.name}"]
        if project.tyler_missing:
            lines.append("- TYLER.md missing - run conform to backfill it")
        elif not project.errands:
            lines.append("- no open errands")
        else:
            for item in project.errands:
                where = f" _({item.section})_" if item.section not in ("Now", "") else ""
                lines.append(f"- [ ] {item.text}{where}")
        if project.tasks_missing:
            lines.append("- TASKS.md missing")
        elif project.decisions:
            lines.append("")
            lines.append("**Blocked on your call:**")
            for item in project.decisions:
                lines.append(f"- [ ] {item.text}")
    lines.append("")
    return "\n".join(lines)


def digest_path(root: Path) -> Path:
    return root / "_tools" / DIGEST_NAME
